vpr: Add make target for source code formatting
SymbiFlow/vtr-verilog-to-routing pull request #18
Opened 2019-03-04 16:35 UTC by kgugala

This PR address 2 point from #13:
* Define clang-format rules for vtr C++
* Create target to automatically format the code

2019-03-04 16:42 UTC, litghost requested changes

2019-03-04 16:42 UTC, litghost commented on vpr/.clang-format
> +IndentWidth: 8
Leave IndentWidth at 4?

2019-03-04 16:42 UTC, litghost commented
Should make this PR directly on https://github.com/verilog-to-routing/vtr-verilog-to-routing ?

2019-03-04 16:50 UTC, kgugala commented on vpr/.clang-format
> +IndentWidth: 8
done

2019-03-04 16:51 UTC, kgugala commented
Sure, I'll open an upstream PR

2019-03-04 16:57 UTC, kgugala commented
Shouldn't we first rebase the code on top of upstream's master?

2019-03-04 16:59 UTC, litghost commented
> Shouldn't we first rebase the code on top of upstream's master?

Sort of.  I believe you mean something like https://github.com/SymbiFlow/vtr-verilog-to-routing/issues/14 ?  I do think pushing the new formatting rules upstream but not running them yet seems okay.

2019-03-04 17:10 UTC, mithro commented
From the vtr devs;
> > One of the outstanding items was to send along reference source files to use as a basis for auto-formatting.
>
> Here are a couple that Vaughn and I think would be good candidates:
>  * https://github.com/verilog-to-routing/vtr-verilog-to-routing/blob/master/vpr/src/base/netlist.h
>  * https://github.com/verilog-to-routing/vtr-verilog-to-routing/blob/master/vpr/src/base/netlist.tpp

2019-03-04 17:16 UTC, kgugala commented
OK, so the formatting rule has to be adjusted to what they prefer

2019-06-06 09:24 UTC, acomodi commented
@mithro @kgugala, I believe this can be closed now that formatting is upstream, right?

2019-06-06 16:46 UTC, closed without merging

2019-06-06 16:46 UTC, mithro commented
@acomodi Correct! Closing.