WIP: RR graph uxsdcxx based reader
SymbiFlow/vtr-verilog-to-routing pull request #340
Opened 2019-12-04 14:42 UTC by litghost

Changes rr graph reader to be based on the interface oriented version of uxsdxx.  Performance of  the XML is improved (25 to 20 seconds), and the capnp based reader is faster (25 to 10 seconds), and half the memory!  See #333 

This PR is for code review of `vpr/src/route/rr_graph_uxsdcxx_interface_impl.h` and to run the CI.

2019-12-04 14:53 UTC, acomodi approved these changes
LGTM.
Just to know, the last two commits are not part of any wip branches right? If so I wonder if it would be better to include them in the fast_rr_read wip branch.

2019-12-04 15:04 UTC, litghost commented
The current structure is intentional.  I wanted to kick off a ci run asap.

More work is required before this can be merged.

2019-12-04 19:47 UTC, litghost commented
VtR + Symbiflow failed because of https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1200.  Once https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1200 is merged, I'll re-run CI and hopefully it will be green.

2019-12-04 21:42 UTC, HackerFoo requested changes
There are a lot of generated files. Can we add the generator to the build process instead?

2019-12-04 21:44 UTC, litghost commented
> There are a lot of generated files. Can we add the generator to the build process instead?

VTR has no python infrastructure, and a base python instance is not sufficient for the generator.

2019-12-04 21:47 UTC, litghost commented
> There are a lot of generated files. Can we add the generator to the build process instead?

To be clear, this was actually discussed with the VTR devs, and they want to check in the generated files, along with a path (e.g. a CMake target) to regenerate the files.

2019-12-05 06:55 UTC, duck2 commented on vpr/src/route/rr_graph_uxsdcxx_interface_impl.h
> +    inline void* get_metadata_meta(int n, void* data) override {
Maybe it's better to generate a `begin/next/end` set of functions in uxsdcxx? We would need one `*data` for the iterator state and one `*data` for the parent state.

2019-12-05 06:55 UTC, duck2 commented on vpr/src/route/rr_graph_uxsdcxx_interface_impl.h
> +        return true;
This can be fixed in the schema.

2019-12-05 23:29 UTC, HackerFoo approved these changes
> > There are a lot of generated files. Can we add the generator to the build process instead?
> 
> To be clear, this was actually discussed with the VTR devs, and they want to check in the generated files, along with a path (e.g. a CMake target) to regenerate the files.

I'm okay with checking in generated files (although it's not ideal) as long as I can easily regenerate them locally.

2020-01-23 01:23 UTC, litghost commented
Superceeded by #365

2020-01-23 01:23 UTC, closed without merging