Integrate new sampling method
SymbiFlow/vtr-verilog-to-routing pull request #342
Opened 2019-12-04 21:26 UTC by HackerFoo

Choose points on a grid as before, but select only points with segment counts in the 50-70 percentile, and keep trying until a number of paths are successfully expanded.

2019-12-04 23:16 UTC, HackerFoo commented
Testing in https://github.com/SymbiFlow/vtr-verilog-to-routing/pull/337

2019-12-04 23:18 UTC, litghost requested changes
Conflicts are present?

2019-12-05 01:15 UTC, HackerFoo commented
@litghost Yes. I rebased my changes onto this branch, so this is expected. Would you prefer that I merge instead?

2019-12-05 01:17 UTC, litghost commented
> @litghost Yes. I rebased my changes onto this branch, so this is expected. Would you prefer that I merge instead?

If you were rebased on this branch, there would be no conflicts?  So by definition, you have not rebased onto the branch?

2019-12-05 19:03 UTC, litghost approved these changes
LGTM

2019-12-06 18:17 UTC, closed without merging