New master+wip
SymbiFlow/vtr-verilog-to-routing pull request #483
Opened 2020-04-24 13:14 UTC by mkurc-ant

New master+wip that incorporates A200T placement issue(s) fix.

Consists of the upstream master with the following wip branches merged:
- wip/lookahead_sampling2
- wip/disable-check-route-option
- wip/update_golden
- wip/add-issue-template
- wip/simbiflow-badger

2020-04-29 18:18 UTC, mkurc-ant commented
I've re-ran the same nightly tests on our current master+wip and it failed in the same way.

2020-04-30 09:13 UTC, acomodi commented
By looking at the commits, this doesn't look like an Octopus merge. I think we should stick with the same way of updating master+wip used for the past updates.

As far as it concerns the nightly tests, I believe that also upstream they go red.

2020-04-30 11:34 UTC, mkurc-ant commented
So it looks like the nightly regression tests fail on our current master+wip as well: https://github.com/SymbiFlow/vtr-verilog-to-routing/pull/484

2020-04-30 16:59 UTC, litghost requested changes
How was this branch generated?  Did you have conflicts during the merge?  @acomodi already mentioned this, but this PR doesn't looke right.

2020-05-04 08:26 UTC, mkurc-ant commented
Ok, I've re-generated the branch using the `update_tool.py` script.

2020-05-04 14:24 UTC, litghost approved these changes
LGTM

2020-05-05 16:18 UTC, merged