Sync with upstream
SymbiFlow/vtr-verilog-to-routing pull request #531
Opened 2020-07-02 15:09 UTC by acomodi

The new master+wip contains the following branches:

wip/add-issue-template
wip/add_back_disable_flag
wip/lookahead_sampling2
wip/symbiflow-badger
wip/update_golden
wip/update_libblifparse

2020-07-06 16:34 UTC, litghost commented
> wip/update_libblifparse

libblifparse update was merged upstream, here https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/1388

2020-07-06 16:37 UTC, acomodi commented
@litghost While running the `all_xc7` tests, I ended up in the same error as in: https://github.com/SymbiFlow/vtr-verilog-to-routing/pull/525#issuecomment-652687353.

It has to do with the recently-added code related to the incremental timing updates.

2020-07-08 17:33 UTC, litghost requested changes
We know this will hit https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1402 , but @HackerFoo suggested a workaround for now with https://github.com/HackerFoo/vtr-verilog-to-routing/commit/7e35d152ce2d1f05aa70bbbc017f9b8f44668138

I'll see if I have time today to debug https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1402

2020-09-14 14:03 UTC, acomodi commented
Superseded by https://github.com/SymbiFlow/vtr-verilog-to-routing/pull/545. Closing

2020-09-14 14:03 UTC, closed without merging