Added changes to write out combinational and sequential timing for Blackbox primitives in SDF
SymbiFlow/vtr-verilog-to-routing pull request #538
Opened 2020-07-08 17:42 UTC by tpagarani

Summary of changes: 
1. Traverse through input and output pins of blackbox primitives and populate timing_arcs, Tsu, Thld, Tco  in local netist_writer data structure. 

2. Store and output the correct reference clock ports in SDF writing.

#### Issue fixed 
https://github.com/SymbiFlow/vtr-verilog-to-routing/issues/537

#### How Has This Been Tested?
- Turned on analysis option and generated the SDF for following test suite
https://github.com/QuickLogic-Corp/symbiflow-arch-defs/tree/quicklogic-upstream-rebase/quicklogic/pp3/tests

- ran the vtr_reg_strong and passed. 

#### Types of changes

- [x ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ X] All new and existing tests passed

2020-07-08 17:44 UTC, litghost commented
Thanks for the fix!  This should be sent to the upstream VTR repo: https://github.com/verilog-to-routing/vtr-verilog-to-routing/

2020-07-15 16:19 UTC, acomodi requested changes
Overall LGTM. Apart from some small fixes related to comments.

An additional thing to do would be to run `make format` as I see Travis failure related to formatting.

I believe once the fixes are in, a PR upstream could be opened.

2020-07-15 16:19 UTC, acomodi commented on vpr/src/base/netlist_writer.cpp
> +typedef std::pair<double, std::string> pair_d;
Probably better to rename pair_d to a more significant name, just for clarity.

2020-07-15 16:19 UTC, acomodi commented on vpr/src/base/netlist_writer.cpp
> +			    //Clock-to-Q delays
Wrong indentation

2020-07-15 16:19 UTC, acomodi commented on vpr/src/base/netlist_writer.cpp
> +                ports_tcq[port_name] = std::make_pair(pin->tco_max,pin->associated_clock_pin->port->name); //pin->tco_max;
Left un-needed code comment

2020-07-15 16:19 UTC, acomodi commented on vpr/src/base/netlist_writer.cpp
> +                ports_tcq[port_name] = std::make_pair(pin->tco_max,pin->associated_clock_pin->port->name); //pin->tco_max;
Left un-needed code comment

2020-07-15 16:25 UTC, acomodi commented
Another thing would also be to add a regression test if possible to check that the write sdf output matches a required golden model.
I have never dealt with checking golden outputs apart from QoR results, but I think that VtR has the infrastructure to add such a test.

2020-10-05 16:59 UTC, litghost commented
This should be sent upstream?  Does this PR has an upstream equivalent?

2020-10-06 03:33 UTC, mithro commented
From what I can see, this is exactly the type of change which should go upstream first.

2020-10-06 07:30 UTC, tpagarani commented
@litghost & @mithro, i am working with @acomodi  to send these changes upstream. They have been moved to 
https://github.com/QuickLogic-Corp/vtr-verilog-to-routing/tree/blackbox_timing_to_upstream

2020-10-06 17:24 UTC, litghost commented
> @litghost & @mithro, i am working with @acomodi to send these changes upstream. They have been moved to
> https://github.com/QuickLogic-Corp/vtr-verilog-to-routing/tree/blackbox_timing_to_upstream

Ah, excellent.   That was not obvious to me.  Sorry for the confusion.

2020-10-30 14:29 UTC, acomodi commented
This was merged upstream. Closing

2020-10-30 14:29 UTC, closed without merging